use_frameworks!

target 'TestPod_Example' do
  pod 'TestPod', :path => '../'

  target 'TestPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
